In [2]:
from fredapi import Fred
import pandas as pd

fred = Fred(api_key='32360bd294fbc8967c6f146354e8b928')

fed_rate = fred.get_series('FEDFUNDS', observation_start='2000-01-01')
fed_rate = fed_rate.reset_index()
fed_rate.columns = ['date', 'fed_rate']

vix = fred.get_series('VIXCLS', observation_start='2000-01-01')
vix = vix.resample('MS').mean().reset_index()
vix.columns = ['date', 'vix']
 
fed_rate
vix

          date        vix
0   2000-01-01  23.202000
1   2000-02-01  23.595500
2   2000-03-01  22.718261
3   2000-04-01  27.164211
4   2000-05-01  26.373182
..         ...        ...
312 2026-01-01  16.179048
313 2026-02-01  19.207000
314 2026-03-01  25.596818
315 2026-04-01  19.811905
316 2026-05-01  16.990000

[317 rows x 2 columns]

In [4]:
from pytrends.request import TrendReq

pytrends = TrendReq()

keywords = ['fintech', 'SaaS', 'biotech', 'AI', 'ecommerce']
pytrends.build_payload(keywords, timeframe='2005-01-01 2014-12-31', geo='US')
trends_df = pytrends.interest_over_time().reset_index()

trends_df

          date  fintech  SaaS  biotech  AI  ecommerce  isPartial
0   2005-01-01        0     4       58  77         25      False
1   2005-02-01        0     2       55  80         24      False
2   2005-03-01        0     3       54  74         25      False
3   2005-04-01        0     2       50  74         24      False
4   2005-05-01        0     2       56  74         23      False
..         ...      ...   ...      ...  ..        ...        ...
115 2014-08-01        1    11       17  85         17      False
116 2014-09-01        1    12       16  93         18      False
117 2014-10-01        1    11       18  92         18      False
118 2014-11-01        1    10       14  96         17      False
119 2014-12-01        1    10       15  91         15      False

[120 rows x 7 columns]